# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Miljkovic/Desktop/Traffic_Lights_Controller/Traffic_Lights/.Xil/Vivado-12716-DESKTOP-EHUO157/incrSyn
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Miljkovic/Desktop/Traffic_Lights_Controller/Traffic_Lights/Traffic_Lights.cache/wt [current_project]
set_property parent.project_path C:/Users/Miljkovic/Desktop/Traffic_Lights_Controller/Traffic_Lights/Traffic_Lights.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/Miljkovic/Desktop/Traffic_Lights_Controller/Traffic_Lights/Traffic_Lights.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/Miljkovic/Desktop/Traffic_Lights_Controller/Traffic_Lights/Traffic_Lights.srcs/sources_1/new/Traffic_Lights.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Miljkovic/Desktop/Traffic_Lights_Controller/Traffic_Lights/Traffic_Lights.srcs/constrs_1/new/Traffic_Lights_Constraints.xdc
set_property used_in_implementation false [get_files C:/Users/Miljkovic/Desktop/Traffic_Lights_Controller/Traffic_Lights/Traffic_Lights.srcs/constrs_1/new/Traffic_Lights_Constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Traffic_Light -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Traffic_Light.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Traffic_Light_utilization_synth.rpt -pb Traffic_Light_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
